name: PR-automerge

on:
  push:
    branches:
      - master

jobs:
  Auto:
    name: Auto-merge
    runs-on: ubuntu-18.04
    steps:
      - uses: unnitallman/pr-auto-merge@v0.1
        with:
          github_token: ${{ secrets.AUTOREBASE_TOKEN }}
