name: Auto-update

on:
  push:
    branches:
      - master

jobs:
  Auto:
    name: Auto-update
    runs-on: ubuntu-18.04
    steps:
      - uses: unnitallman/auto-update@v2.1.4
        with:
          github_token: ${{ secrets.AUTOREBASE_TOKEN }}
