name: PR-automerge

on: 
  status:
  pull_request:
    types: [ labeled ]

jobs:
  Auto:
    name: Auto-merge
    runs-on: ubuntu-18.04
    steps:
      - uses: unnitallman/pr-auto-merge@v0.90
        if: contains(github.event.pull_request.labels.*.name, 'mergepr')
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOREBASE_TOKEN }}
