name: PR-automerge

on:
  pull_request:
    types: [ opened, reopened, labeled ]

jobs:
  Auto:
    name: Auto-merge
    runs-on: ubuntu-18.04
    steps:
      - uses: unnitallman/pr-auto-merge@v0.40
        if: contains(github.event.pull_request.labels.*.name, 'mergepr')
        with:
          github_token: ${{ secrets.AUTOREBASE_TOKEN }}
